version: '3.8'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4445:4444"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - selenium
    environment:
      - DISPLAY=:99
